services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    networks:
      - "proxy"
    command:
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
        # - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
        # - "--entryPoints.websecure.forwardedHeaders.insecure"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=saiful@pingsut.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs/:/logs/"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.semut.pingsut.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.middlewares=traefik-auth,traefik-compress"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=ipul:$$apr1$$jAzACfCs$$myU9dZT3.Y1JG4J17jHHd/"
      - "traefik.http.middlewares.traefik-compress.compress=true"

networks:
  proxy:
    external: {}
